---
rmq/rabbitmq-server-generic-unix-3.3.1.tar.gz:
  object_id: 047a2c6a-2dfe-4160-99f1-40b8af04e1f5
  sha: be2667bcead3182cf8251c3537ac7c7f07940794
  size: 3852681
libyaml/yaml-0.1.5.tar.gz:
  object_id: d0e9d57c-2412-42f0-9391-1c060bdf793e
  sha: 8b78cb9f759c7d80db8a7328c0ebecfe34fde737
  size: 504897
ruby/bundler-1.6.2.gem:
  object_id: 181b74c4-a2f8-412d-8cf8-e9ff844ec537
  sha: 2853e0a4b668329c6b429a5a3eb7c2daa2feb2c5
  size: 293376
ruby/ruby-2.0.0-p481.tar.gz:
  object_id: 0b346691-32b4-4318-9011-1c503a4e16e9
  sha: dded7b7349d59feb83d4f774b2ddec23eeab7978
  size: 13586757
ruby/rubygems-2.2.2.tgz:
  object_id: 2a4a3af8-b1d2-44bd-a27a-245502370bac
  sha: 3fad1f6415ba92594fe4b42903f3a2938cefbadf
  size: 414111
erlang/otp_src_17.0.tar.gz:
  object_id: 0d1b70cd-6e45-4102-b242-d9c4556b69bf
  sha: de4d195e3c7d8ea0b3d2bc73b937d3dcad37b25a
  size: 66640875
